name: Publish JQuill to GitHub Packages

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - ci-test
  pull_request:
    branches:
      - main
      - ci-test

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin
          server-id: github
          settings-path: ${{ github.workspace }}
      - run: mvn clean deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
